In [1]:
import numpy

In [2]:
n=numpy.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

In [5]:
[[123,45,566],[],[]]


[[123, 45, 566], [], []]

In [7]:
y=numpy.asarray([[123,45,566],[],[]])

In [8]:
y


array([list([123, 45, 566]), list([]), list([])], dtype=object)

In [9]:
type(y)

numpy.ndarray

In [1]:
>>> from PIL import Image


In [12]:
!pip3 install opencv-python

    100% |████████████████████████████████| 25.0MB 55kB/s 
  Using cached https://files.pythonhosted.org/packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl


In [3]:
import cv2


In [15]:
img1=cv2.imread("smallgray.png",0)

In [16]:
img1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
img=cv2.imread("smallgray.png",1)
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [8]:
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [9]:
cv2.imwrite("sampleimg.png",img)

True

In [10]:
cv2.imread("colors.png")

array([[[255,   0,   0],
        [254,   0,   0],
        [253,   0,   1],
        ...,
        [  2,   0, 252],
        [  1,   0, 253],
        [  0,   0, 254]],

       [[255,   0,   0],
        [254,   0,   0],
        [253,   0,   1],
        ...,
        [  2,   0, 252],
        [  1,   0, 253],
        [  0,   0, 254]],

       [[255,   1,   0],
        [254,   1,   0],
        [253,   1,   1],
        ...,
        [  2,   1, 252],
        [  1,   1, 253],
        [  0,   1, 254]],

       ...,

       [[255, 252,   0],
        [254, 252,   0],
        [253, 252,   1],
        ...,
        [  2, 252, 252],
        [  1, 252, 253],
        [  0, 252, 254]],

       [[255, 253,   0],
        [254, 253,   0],
        [253, 253,   1],
        ...,
        [  2, 253, 252],
        [  1, 253, 253],
        [  0, 253, 254]],

       [[255, 254,   0],
        [254, 254,   0],
        [253, 254,   1],
        ...,
        [  2, 254, 252],
        [  1, 254, 253],
        [  0, 254, 254]]

In [11]:
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [12]:
img[:,4]

array([[143, 143, 143],
       [147, 147, 147],
       [182, 182, 182]], dtype=uint8)

In [14]:
img1

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [17]:
img1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [18]:
img1[2,3]

97

In [21]:
for i in img1:
    for j in i :
        print(j)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [22]:
for i in img1.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [23]:
img


array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [24]:
img1


array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [29]:
import numpy

In [30]:
imgh=numpy.hstack((img1,img1))

In [31]:
imgh

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [32]:
imgh=numpy.vstack((img1,img1))

In [35]:
print(imgh)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [36]:
print(img1)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [49]:
lst=numpy.hsplit(imgh,5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [43]:
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [40]:
print(lst)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
